# Generated by Django 3.0.7 on 2020-09-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200919_1633'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='Book',
        ),
    ]
