# Generated by Django 2.2.6 on 2020-09-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200921_1706'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
    ]
